# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"(\n\x08Schedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x0f\n\rShowtimeEmpty2a\n\x08Showtime\x12,\n\x0bGetSchedule\x12\x0e.ShowtimeEmpty\x1a\t.Schedule\"\x00\x30\x01\x12\'\n\x11GetScheduleByDate\x12\x05.Date\x1a\t.Schedule\"\x00\x62\x06proto3')



_SCHEDULE = DESCRIPTOR.message_types_by_name['Schedule']
_DATE = DESCRIPTOR.message_types_by_name['Date']
_SHOWTIMEEMPTY = DESCRIPTOR.message_types_by_name['ShowtimeEmpty']
Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

ShowtimeEmpty = _reflection.GeneratedProtocolMessageType('ShowtimeEmpty', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTIMEEMPTY,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ShowtimeEmpty)
  })
_sym_db.RegisterMessage(ShowtimeEmpty)

_SHOWTIME = DESCRIPTOR.services_by_name['Showtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULE._serialized_start=18
  _SCHEDULE._serialized_end=58
  _DATE._serialized_start=60
  _DATE._serialized_end=80
  _SHOWTIMEEMPTY._serialized_start=82
  _SHOWTIMEEMPTY._serialized_end=97
  _SHOWTIME._serialized_start=99
  _SHOWTIME._serialized_end=196
# @@protoc_insertion_point(module_scope)
